### ISSUE TITLE
Document the setup of Keras using Oficial TF docker

### ISSUE THREAD

**Issue by harpomaxx** [harpomaxx/image-processing#1]

**Comment by torresmia** [comment]
1- ssh connection to samson with port forwarding
_$ ssh -L 8888:127.0.0.1:8888 -L 6007:127.0.0.1:6007 user@200.12.137.13 -p 22037 -C_

2- run docker container for tensorflow + gpu + jupyter image
_$ docker run --rm --gpus all -it -p 8888:8888 -p 6007:6007 tensorflow/tensorflow:latest-gpu-jupyter_ 

3- open vscode (extensions needed: Python and Jupyter)
- Select Jupyter Server -> Existing -> paste URL given by the docker command
- Select Kernel -> (Remote) Jupyter Kernel

4- Ready to run a local jupyter notebook (or create a new one)
